Algoritmo "semnome"
Var
p1,p2,media:real
nome1,nome2:caractere
Inicio
 escreval("calculadora de idade media das pessoa")
 Escreval("digite o nome da primeira pessoa")
 leia(nome1)
 escreval("digite o nome da segunda pessoa")
 leia(nome2)
 escreval("digite sua idade ",nome1)
 leia (p1)
 escreval("digite sua idade ",nome2)
 leia (p2)
 media<- ((p1+p2)/2)
 escreval(nome1," e ",nome2," possuem uma idade media de",media,"anos")
Fimalgoritmo