Algoritmo "menor numero"
Var
a,b,c:inteiro
Inicio
 escreval ("calcule automaticamente o menor numero")
 Escreval("digite o valor de a")
 leia(a)
 escreval ("digite o valor de b")
 leia(B)
 escreval ("digite o valor de c")
 leia(c)

  se (a<b) e (a<c) entao
    escreva ("valor=",a)
    senao
     se (b<a) e (b<c) entao
       escreva ("valor=",b)
       senao
        escreva ("valor=",c)
     fimse
  fimse
Fimalgoritmo